/** Merge this resource fragment into the root i18next resources during PA integration. */
export const adminImportResources = {
  en: {
    translation: {
      adminImport: {
        authExpired: 'Your session has expired. Sign in again before resuming this import.',
        cancel: 'Cancel import',
        cancelFailed: 'We could not cancel this import. Your selected files are still saved in this browser.',
        corruptFile: 'We could not open this file, so it was skipped.',
        dropzoneDescription: 'JPEG, PNG, or WebP. Private details, such as location, are removed before your photos are sent.',
        dropzoneOriginalDescription: 'JPEG, PNG, or WebP. Original files are also saved so visitors can download them.',
        dropzoneLabel: 'Drop photos here or choose files',
        duplicateFile: 'This photo is already in this gallery, so it was skipped.',
        duplicateConflict: 'A photo was added to this gallery during your import. Cancel this import and choose the files again to skip duplicates.',
        encoding: 'Getting your photos ready…',
        eta: 'About {{seconds}} seconds remaining',
        failed: 'The import stopped before it could finish. Check your connection, then try Resume import. Your chosen files are still saved in this browser.',
        galleryUnavailable: 'This gallery is no longer available. Return to your galleries to check its status.',
        pause: 'Pause import',
        paused: 'Import paused',
        progress: 'Import progress',
        quota: 'This gallery cannot accept all these photos. Add fewer photos or check your limits.',
        storageQuota: 'Photo storage is full. Free space or raise your site limit, then resume or cancel this import.',
        d1DailyQuota: 'Cloudflare D1 has reached its daily read or write limit. Check D1 usage in Cloudflare. On the Free plan, wait for the midnight UTC reset or upgrade the Workers plan. Then resume the import if offered, or select your files again.',
        resourceLimit: 'Cloudflare stopped this photo upload because the Worker exceeded a resource limit. The import is paused. Try Resume; if it repeats, check Worker CPU and memory usage.',
        recoveryTitle: 'Unfinished photos ({{count}})',
        recoveryDescription: 'The original browser import can no longer be resumed here. Select the original files below to complete these photos. Ready photos stay in place, and only missing copies are uploaded.',
        recoveryDropzone: 'Select originals to finish unfinished photos',
        recoveryFinalize: 'Finish unfinished photos',
        recoveryDropzoneDescription: 'You can select the full original set; files already completed are ignored. Keep this page open until recovery finishes.',
        recoveryProgress: 'Completing {{completed}} of {{total}} photos…',
        recoveryComplete: 'The selected unfinished photos are now ready. Check the gallery counts above before publishing.',
        recoveryNoMatch: 'None of the selected files matched the unfinished originals. Select the exact original files shown above.',
        recoveryPartial: '{{count}} photos still need their exact original files. Select them above to continue.',
        recoveryFailed: 'Recovery stopped. Completed copies are saved. Select the original files again to retry the unfinished photos.',
        resume: 'Resume import',
        start: 'Start import for {{gallery}}',
        replacementTitle: 'Replace a selected photo',
        replacementDescription: 'Choose the edited version of this photo. The current photo stays visible until the new one is ready. Its favorites, retouch selection, place in the gallery, and link will stay the same.',
        replacementFaceWarning: 'Use an edited version of the same photo. The existing face-search matches are kept and are not recalculated when you replace it.',
        replacementDropzone: 'Choose one edited photo',
        replacementSinglePhoto: 'Choose just one photo to replace this image.',
        replacementFinishing: 'Putting the edited photo in the gallery…',
        replacementDone: 'The edited photo is now in the gallery.',
        replacementBack: 'Back to selected photos',
        replacementError: 'The new photo was uploaded, but the replacement could not finish. Try again here or from the selected photos page.',
        replacementRetry: 'Finish replacement',
        unsupportedFile: 'Only JPEG, PNG, and WebP files can be imported.',
        originalTooLarge: 'This original is larger than 100 MB. Export a smaller file before importing it.',
      },
    },
  },
  fr: {
    translation: {
      adminImport: {
        authExpired: 'Votre session a expiré. Reconnectez-vous avant de reprendre cette importation.',
        cancel: "Annuler l'importation",
        cancelFailed: 'Nous n’avons pas pu annuler cette importation. Les fichiers sélectionnés restent enregistrés dans ce navigateur.',
        corruptFile: 'Nous n’avons pas pu ouvrir ce fichier. Il a été ignoré.',
        dropzoneDescription: 'JPEG, PNG ou WebP. Les données privées, comme la localisation, sont retirées avant l’envoi des photos.',
        dropzoneOriginalDescription: 'JPEG, PNG ou WebP. Les fichiers originaux sont aussi conservés pour le téléchargement.',
        dropzoneLabel: 'Déposez des photos ici ou choisissez des fichiers',
        duplicateFile: 'Cette photo est déjà dans cette galerie. Elle a été ignorée.',
        duplicateConflict: 'Une photo a été ajoutée à cette galerie pendant votre importation. Annulez cette importation, puis choisissez de nouveau les fichiers pour ignorer les doublons.',
        encoding: 'Préparation de vos photos…',
        eta: 'Environ {{seconds}} secondes restantes',
        failed: "L’importation s’est arrêtée avant la fin. Vérifiez votre connexion, puis choisissez Reprendre l’importation. Les fichiers sélectionnés restent enregistrés dans ce navigateur.",
        galleryUnavailable: 'Cette galerie n’est plus disponible. Revenez à vos galeries pour vérifier son état.',
        pause: "Mettre l'importation en pause",
        paused: 'Importation en pause',
        progress: "Progression de l'importation",
        quota: 'Cette galerie ne peut pas accueillir toutes ces photos. Ajoutez-en moins ou vérifiez vos limites.',
        storageQuota: 'Le stockage des photos est plein. Libérez de l’espace ou augmentez la limite du site, puis reprenez ou annulez cette importation.',
        d1DailyQuota: 'Cloudflare D1 a atteint sa limite quotidienne de lectures ou d’écritures. Vérifiez l’utilisation de D1 dans Cloudflare. Avec l’offre gratuite, attendez la remise à zéro à minuit UTC ou passez à l’offre Workers payante. Reprenez ensuite l’importation si l’option est offerte, ou sélectionnez de nouveau vos fichiers.',
        resourceLimit: 'Cloudflare a arrêté l’envoi de cette photo, car le Worker a dépassé une limite de ressources. L’importation est en pause. Essayez Reprendre; si le problème revient, vérifiez l’utilisation du processeur et de la mémoire du Worker.',
        recoveryTitle: 'Photos incomplètes ({{count}})',
        recoveryDescription: 'L’importation d’origine ne peut plus être reprise dans ce navigateur. Sélectionnez les fichiers originaux ci-dessous pour terminer ces photos. Les photos prêtes restent en place et seules les copies manquantes sont envoyées.',
        recoveryDropzone: 'Sélectionner les originaux pour terminer les photos incomplètes',
        recoveryFinalize: 'Terminer les photos incomplètes',
        recoveryDropzoneDescription: 'Vous pouvez sélectionner tous les fichiers originaux; les photos déjà prêtes seront ignorées. Gardez cette page ouverte jusqu’à la fin de la reprise.',
        recoveryProgress: 'Finalisation de {{completed}} photo(s) sur {{total}}…',
        recoveryComplete: 'Les photos incomplètes sélectionnées sont maintenant prêtes. Vérifiez les compteurs de la galerie ci-dessus avant de publier.',
        recoveryNoMatch: 'Aucun fichier sélectionné ne correspond aux originaux incomplets. Sélectionnez les fichiers originaux exacts indiqués ci-dessus.',
        recoveryPartial: 'Il reste {{count}} photo(s) à terminer avec leurs fichiers originaux exacts. Sélectionnez-les ci-dessus pour continuer.',
        recoveryFailed: 'La reprise s’est arrêtée. Les copies terminées sont conservées. Sélectionnez de nouveau les fichiers originaux pour réessayer les photos incomplètes.',
        resume: "Reprendre l'importation",
        start: "Démarrer l'importation pour {{gallery}}",
        replacementTitle: 'Remplacer une photo sélectionnée',
        replacementDescription: 'Choisissez la version retouchée. La photo actuelle reste visible pendant la préparation. Ses coups de cœur, sa sélection pour retouche, sa place dans la galerie et son lien seront conservés.',
        replacementFaceWarning: 'Utilisez une version retouchée de la même photo. Les correspondances de recherche faciale existantes sont conservées et ne sont pas recalculées lors du remplacement.',
        replacementDropzone: 'Choisir une seule photo retouchée',
        replacementSinglePhoto: 'Choisissez une seule photo pour remplacer cette image.',
        replacementFinishing: 'Ajout de la photo retouchée dans la galerie…',
        replacementDone: 'La photo retouchée est maintenant dans la galerie.',
        replacementBack: 'Retour aux photos sélectionnées',
        replacementError: 'La nouvelle photo est envoyée, mais le remplacement n’est pas terminé. Réessayez ici ou depuis les photos sélectionnées.',
        replacementRetry: 'Terminer le remplacement',
        unsupportedFile: 'Seuls les fichiers JPEG, PNG et WebP peuvent être importés.',
        originalTooLarge: 'Cet original dépasse 100 Mo. Exportez un fichier plus petit avant de l’importer.',
      },
    },
  },
} as const;
