/** Merge this resource fragment into the root i18next resources during PA integration. */
export const adminImportResources = {
  en: {
    translation: {
      adminImport: {
        cancel: 'Cancel import',
        corruptFile: 'We could not open this file, so it was skipped.',
        dropzoneDescription: 'JPEG, PNG, or WebP. Private details, such as location, are removed before your photos are sent.',
        dropzoneOriginalDescription: 'JPEG, PNG, or WebP. Original files are also saved so visitors can download them.',
        dropzoneLabel: 'Drop photos here or choose files',
        encoding: 'Getting your photos ready…',
        eta: 'About {{seconds}} seconds remaining',
        failed: 'The import paused. You can resume it after checking your connection.',
        pause: 'Pause import',
        paused: 'Import paused',
        progress: 'Import progress',
        quota: 'This gallery cannot accept all these photos. Add fewer photos or check your limits.',
        resume: 'Resume import',
        start: 'Start import',
        replacementTitle: 'Replace a selected photo',
        replacementDescription: 'Choose the edited version of this photo. The current photo stays visible until the new one is ready. Its favorites, retouch selection, place in the gallery, and link will stay the same.',
        replacementFaceWarning: 'Use an edited version of the same photo. The existing face-search matches are kept and are not recalculated when you replace it.',
        replacementDropzone: 'Choose one edited photo',
        replacementSinglePhoto: 'Choose just one photo to replace this image.',
        replacementFinishing: 'Putting the edited photo in the gallery…',
        replacementDone: 'The edited photo is now in the gallery.',
        replacementBack: 'Back to selected photos',
        replacementError: 'The new photo was uploaded, but the replacement could not finish. Try again here or from the selected photos page.',
        replacementRetry: 'Finish replacement',
        unsupportedFile: 'Only JPEG, PNG, and WebP files can be imported.',
        originalTooLarge: 'This original is larger than 100 MB. Export a smaller file before importing it.',
      },
    },
  },
  fr: {
    translation: {
      adminImport: {
        cancel: "Annuler l'importation",
        corruptFile: 'Nous n’avons pas pu ouvrir ce fichier. Il a été ignoré.',
        dropzoneDescription: 'JPEG, PNG ou WebP. Les données privées, comme la localisation, sont retirées avant l’envoi des photos.',
        dropzoneOriginalDescription: 'JPEG, PNG ou WebP. Les fichiers originaux sont aussi conservés pour le téléchargement.',
        dropzoneLabel: 'Déposez des photos ici ou choisissez des fichiers',
        encoding: 'Préparation de vos photos…',
        eta: 'Environ {{seconds}} secondes restantes',
        failed: "L'importation est en pause. Vous pouvez la reprendre après avoir vérifié votre connexion.",
        pause: "Mettre l'importation en pause",
        paused: 'Importation en pause',
        progress: "Progression de l'importation",
        quota: 'Cette galerie ne peut pas accueillir toutes ces photos. Ajoutez-en moins ou vérifiez vos limites.',
        resume: "Reprendre l'importation",
        start: "Démarrer l'importation",
        replacementTitle: 'Remplacer une photo sélectionnée',
        replacementDescription: 'Choisissez la version retouchée. La photo actuelle reste visible pendant la préparation. Ses coups de cœur, sa sélection pour retouche, sa place dans la galerie et son lien seront conservés.',
        replacementFaceWarning: 'Utilisez une version retouchée de la même photo. Les correspondances de recherche faciale existantes sont conservées et ne sont pas recalculées lors du remplacement.',
        replacementDropzone: 'Choisir une seule photo retouchée',
        replacementSinglePhoto: 'Choisissez une seule photo pour remplacer cette image.',
        replacementFinishing: 'Ajout de la photo retouchée dans la galerie…',
        replacementDone: 'La photo retouchée est maintenant dans la galerie.',
        replacementBack: 'Retour aux photos sélectionnées',
        replacementError: 'La nouvelle photo est envoyée, mais le remplacement n’est pas terminé. Réessayez ici ou depuis les photos sélectionnées.',
        replacementRetry: 'Terminer le remplacement',
        unsupportedFile: 'Seuls les fichiers JPEG, PNG et WebP peuvent être importés.',
        originalTooLarge: 'Cet original dépasse 100 Mo. Exportez un fichier plus petit avant de l’importer.',
      },
    },
  },
} as const;
