export const portfolioResources = {
  en: { admin: { portfolio: {
    title: 'Portfolio', description: 'Create collections for your work. Each collection has its own page, cover and photos.',
    loading: 'Loading portfolio…', error: 'This change could not be saved. Check the details and try again.',
    service: 'Service category', titleFr: 'Collection title in French', titleEn: 'Collection title in English',
    descriptionFr: 'Collection description in French', descriptionEn: 'Collection description in English', slug: 'Link name',
    collectionOrder: 'Collection display order', cover: 'Cover photo', firstPhoto: 'First published photo',
    visible: 'Show this collection in the public portfolio', viewPublic: 'View public collection',
    publishHint: 'Add a photo before publishing this collection.',
    altFr: 'Photo description in French', altEn: 'Photo description in English', order: 'Photo display order',
    upload: 'Retry photo upload', uploadHint: 'Photos are prepared in several sizes. For an interrupted upload, select the same original file.',
    addCollection: 'Create collection', collections: 'Collections', empty: 'No collections yet.',
    manage: 'Manage collection', back: 'Back to collections', draft: 'Draft', published: 'Published',
    photoCount_one: '{{count}} photo', photoCount_other: '{{count}} photos',
    photos: 'Collection photos', addPhotos: 'Add photos', emptyPhotos: 'No photos yet.',
    uploadProgress: '{{done}} of {{total}} photos uploaded', pending: 'Upload incomplete',
    save: 'Save details', remove: 'Remove photo', cancel: 'Cancel',
    removeTitle: 'Remove this photo?', removeBody: 'The photo disappears from the public collection immediately. Stored sizes are removed in the background.',
    deleteCollection: 'Delete collection', deleteCollectionTitle: 'Delete this collection?',
    deleteCollectionBody: 'The collection and its photos disappear from the public portfolio immediately. Stored sizes are removed in the background.',
  } } },
  fr: { admin: { portfolio: {
    title: 'Portfolio', description: 'Créez des collections pour présenter votre travail. Chacune a sa page, sa couverture et ses photos.',
    loading: 'Chargement du portfolio…', error: 'Impossible d’enregistrer ce changement. Vérifiez les détails et réessayez.',
    service: 'Catégorie de service', titleFr: 'Titre de la collection en français', titleEn: 'Titre de la collection en anglais',
    descriptionFr: 'Description de la collection en français', descriptionEn: 'Description de la collection en anglais', slug: 'Nom du lien',
    collectionOrder: 'Ordre des collections', cover: 'Photo de couverture', firstPhoto: 'Première photo publiée',
    visible: 'Afficher cette collection dans le portfolio public', viewPublic: 'Voir la collection publique',
    publishHint: 'Ajoutez une photo avant de publier cette collection.',
    altFr: 'Description de la photo en français', altEn: 'Description de la photo en anglais', order: 'Ordre des photos',
    upload: 'Reprendre le téléversement', uploadHint: 'Les photos sont préparées en plusieurs tailles. Pour reprendre un envoi interrompu, choisissez le même fichier original.',
    addCollection: 'Créer la collection', collections: 'Collections', empty: 'Aucune collection pour le moment.',
    manage: 'Gérer la collection', back: 'Retour aux collections', draft: 'Brouillon', published: 'Publiée',
    photoCount_one: '{{count}} photo', photoCount_other: '{{count}} photos',
    photos: 'Photos de la collection', addPhotos: 'Ajouter des photos', emptyPhotos: 'Aucune photo pour le moment.',
    uploadProgress: 'Photos envoyées : {{done}} / {{total}}', pending: 'Téléversement incomplet',
    save: 'Enregistrer', remove: 'Retirer la photo', cancel: 'Annuler',
    removeTitle: 'Retirer cette photo?', removeBody: 'La photo disparaît immédiatement de la collection publique. Les tailles stockées sont supprimées en arrière-plan.',
    deleteCollection: 'Supprimer la collection', deleteCollectionTitle: 'Supprimer cette collection?',
    deleteCollectionBody: 'La collection et ses photos disparaissent immédiatement du portfolio public. Les tailles stockées sont supprimées en arrière-plan.',
  } } },
} as const;
