/**
 * PA-owned resource fragment. The integration owner merges each language into
 * the existing `translation` resource before mounting AdminRoutes.
 */
export const adminResourceFragment = {
  en: {
    admin: {
      dashboard: {
        description: 'Your event workspace is ready for the next steps.',
        events: 'Event management',
        eventsDescription: 'Create, publish, and import galleries from this workspace.',
        title: 'Dashboard',
      },
      demo: {
        dashboardBody: 'Browse the same event structure a photographer sees. Creation, editing, imports, uploads, publishing, face indexing, and deletion are blocked by the server for this session.',
        dashboardTitle: 'Explore the workflow safely.',
        eyebrow: 'Live product demonstration',
        importBody: 'Import and publication tools are visible only to the owner account. This demo identity cannot upload files or change Cloudflare data.',
        importTitle: 'Imports are disabled in read-only mode',
        inspect: 'Inspect',
        loginBody: 'Use the published credentials below. This account can browse the dashboard but cannot create, edit, upload, publish, or delete anything.',
        loginTitle: 'Explore the photographer workspace.',
        ownerLink: 'Photographer? Use the owner sign-in',
        readOnlyBanner: 'Demo mode — read-only. Every data-changing request is blocked by the Worker.',
        readOnlyLabel: 'Read-only event details',
        status: 'Status',
        submit: 'Enter the read-only demo',
        username: 'Username',
      },
      events: {
        access: 'Gallery access',
        allowDownloads: 'Allow photo downloads',
        back: 'Back to events',
        create: 'Create draft event',
        createDescription: 'Start with a private draft. Import and review the photos before publishing.',
        createError: 'The event could not be created. Review the fields and try again.',
        createTitle: 'New event',
        date: 'Event date and time',
        description: 'Description',
        empty: 'No events yet. Create the first draft above.',
        faceSearch: 'Enable optional face search',
        import: 'Import photos',
        keepOriginals: 'Keep original files',
        listError: 'Events could not be loaded.',
        listTitle: 'Your events',
        loading: 'Loading events…',
        newPassword: 'New guest password (leave empty to keep the current password)',
        notFound: 'This event could not be found.',
        options: 'Gallery options',
        password: 'Guest password (8 characters minimum)',
        protected: 'Protected by password',
        public: 'Public',
        retention: 'Retention in days',
        retentionHint: 'Leave blank for unlimited gallery retention.',
        retentionUnlimited: 'Keep this gallery indefinitely',
        unlimited: 'Unlimited',
        save: 'Save settings',
        settings: 'Settings',
        settingsTitle: 'Settings — {{title}}',
        title: 'Event title',
        updateError: 'The settings could not be saved. Review the fields and try again.',
        updated: 'Settings saved.',
        view: 'View gallery',
        visibility: {
          draft: 'Draft',
          published: 'Published',
          unlisted: 'Unlisted',
        },
      },
      language: 'Français',
      login: {
        body: 'Sign in with the private owner credential configured for this deployment.',
        configuration: 'Administration is locked because authentication is not configured. Add the required Worker secrets, then redeploy.',
        error: 'We could not sign you in. Check your password and try again.',
        eyebrow: 'Owner access',
        demoLink: 'Curious? Open the read-only demo',
        password: 'Password',
        submit: 'Sign in',
        title: 'Photographer sign in',
        turnstileUnavailable: 'The security check is not ready. Please refresh and try again.',
      },
      logout: 'Sign out',
      navigation: {
        dashboard: 'Dashboard',
      },
      signedInAs: 'Signed in as {{subject}}',
      skipToContent: 'Skip to content',
      theme: 'Use dark theme',
      themeLight: 'Use light theme',
    },
  },
  fr: {
    admin: {
      dashboard: {
        description: 'Votre espace événement est prêt pour les prochaines étapes.',
        events: 'Gestion des événements',
        eventsDescription: 'Créez, publiez et importez les galeries depuis cet espace.',
        title: 'Tableau de bord',
      },
      demo: {
        dashboardBody: "Parcourez la même structure d'événements qu'un photographe. La création, la modification, les imports, les téléversements, la publication, l'indexation faciale et la suppression sont bloqués par le serveur pour cette session.",
        dashboardTitle: 'Explorez le parcours en toute sécurité.',
        eyebrow: 'Démonstration produit en direct',
        importBody: "Les outils d'import et de publication sont réservés au compte propriétaire. Cette identité de démo ne peut ni téléverser de fichiers ni modifier les données Cloudflare.",
        importTitle: 'Imports désactivés en lecture seule',
        inspect: 'Inspecter',
        loginBody: "Utilisez les identifiants publics ci-dessous. Ce compte peut parcourir le tableau de bord, mais ne peut rien créer, modifier, téléverser, publier ou supprimer.",
        loginTitle: "Explorez l'espace photographe.",
        ownerLink: 'Photographe? Utiliser la connexion propriétaire',
        readOnlyBanner: 'Mode démo — lecture seule. Toute requête qui modifierait des données est bloquée par le Worker.',
        readOnlyLabel: "Détails de l'événement en lecture seule",
        status: 'État',
        submit: 'Entrer dans la démo en lecture seule',
        username: "Nom d'utilisateur",
      },
      events: {
        access: 'Accès à la galerie',
        allowDownloads: 'Autoriser le téléchargement des photos',
        back: 'Retour aux événements',
        create: "Créer l'événement brouillon",
        createDescription: "Commencez avec un brouillon privé. Importez et révisez les photos avant de le publier.",
        createError: "Impossible de créer l'événement. Vérifiez les champs et réessayez.",
        createTitle: 'Nouvel événement',
        date: "Date et heure de l'événement",
        description: 'Description',
        empty: 'Aucun événement. Créez votre premier brouillon ci-dessus.',
        faceSearch: 'Activer la recherche faciale facultative',
        import: 'Importer des photos',
        keepOriginals: 'Conserver les fichiers originaux',
        listError: 'Impossible de charger les événements.',
        listTitle: 'Vos événements',
        loading: 'Chargement des événements…',
        newPassword: "Nouveau mot de passe invité (laissez vide pour conserver l'actuel)",
        notFound: "Cet événement est introuvable.",
        options: 'Options de la galerie',
        password: 'Mot de passe invité (8 caractères minimum)',
        protected: 'Protégée par mot de passe',
        public: 'Publique',
        retention: 'Conservation en jours',
        retentionHint: 'Laissez vide pour une conservation illimitée de la galerie.',
        retentionUnlimited: 'Conserver cette galerie sans limite de durée',
        unlimited: 'Illimitée',
        save: 'Enregistrer les réglages',
        settings: 'Réglages',
        settingsTitle: 'Réglages — {{title}}',
        title: "Titre de l'événement",
        updateError: "Impossible d'enregistrer les réglages. Vérifiez les champs et réessayez.",
        updated: 'Réglages enregistrés.',
        view: 'Voir la galerie',
        visibility: {
          draft: 'Brouillon',
          published: 'Publiée',
          unlisted: 'Non répertoriée',
        },
      },
      language: 'English',
      login: {
        body: 'Connectez-vous avec le secret privé du propriétaire configuré pour ce déploiement.',
        configuration: "L'administration est verrouillée parce que l'authentification n'est pas configurée. Ajoutez les secrets Worker requis, puis redéployez.",
        error: 'La connexion a échoué. Vérifiez votre mot de passe et réessayez.',
        eyebrow: 'Accès propriétaire',
        demoLink: 'Curieux? Ouvrir la démo en lecture seule',
        password: 'Mot de passe',
        submit: 'Se connecter',
        title: 'Connexion photographe',
        turnstileUnavailable: 'La vérification de sécurité est indisponible. Actualisez puis réessayez.',
      },
      logout: 'Se déconnecter',
      navigation: {
        dashboard: 'Tableau de bord',
      },
      signedInAs: 'Connecté en tant que {{subject}}',
      skipToContent: 'Aller au contenu',
      theme: 'Utiliser le thème sombre',
      themeLight: 'Utiliser le thème clair',
    },
  },
} as const;
