/**
 * PA-owned resource fragment. The integration owner merges each language into
 * the existing `translation` resource before mounting AdminRoutes.
 */
export const adminResourceFragment = {
  en: {
    admin: {
      dashboard: {
        description: 'Your event workspace is ready for the next steps.',
        events: 'Event management',
        eventsDescription: 'Create, publish, and import galleries from this workspace.',
        title: 'Dashboard',
      },
      demo: {
        dashboardBody: 'Browse the same event structure a photographer sees. Creation, editing, imports, uploads, publishing, face indexing, and deletion are blocked by the server for this session.',
        dashboardTitle: 'Explore the workflow safely.',
        eyebrow: 'Live product demonstration',
        importBody: 'Import and publication tools are visible only to the owner account. This demo identity cannot upload files or change Cloudflare data.',
        importTitle: 'Imports are disabled in read-only mode',
        inspect: 'View gallery settings',
        capabilitiesTitle: 'Owner actions',
        capabilitiesBody: 'These are the same next steps available to an owner. They stay visible here so you can understand the workflow, but the Worker blocks every action in this demo.',
        formPlayground: 'Try every option freely. Only the final save action is disabled, and the Worker remains the security boundary.',
        createGallery: 'Create a gallery',
        importPhotos: 'Import photos',
        publishGallery: 'Publish gallery',
        loginBody: 'Use the published credentials below. This account can browse the dashboard but cannot create, edit, upload, publish, or delete anything.',
        loginTitle: 'Explore the photographer workspace.',
        ownerLink: 'Photographer? Use the owner sign-in',
        readOnlyBanner: 'Demo mode — read-only. Every data-changing request is blocked by the Worker.',
        readOnlyLabel: 'Read-only event details',
        status: 'Status',
        submit: 'Enter the read-only demo',
        username: 'Username',
      },
      events: {
        access: 'Gallery access',
        allowDownloads: 'Allow photo downloads',
        back: 'Back to events',
        create: 'Create draft event',
        createDescription: 'Start with a private draft. Import and review the photos before publishing.',
        createError: 'The event could not be created. Review the fields and try again.',
        createTitle: 'New event',
        date: 'Event date and time',
        description: 'Description',
        empty: 'No events yet. Create the first draft above.',
        faceSearch: 'Enable optional face search',
        nearbySearch: 'Include photos from nearby moments',
        nearbySearchHint: 'Available only with face search. It adds same-gallery photos captured around a possible match.',
        showPhotoMetadata: 'Let visitors view photo metadata',
        import: 'Import photos',
        keepOriginals: 'Keep original files',
        listError: 'Events could not be loaded.',
        listTitle: 'Your events',
        loading: 'Loading events…',
        newPassword: 'New guest password (leave empty to keep the current password)',
        notFound: 'This event could not be found.',
        options: 'Gallery options',
        password: 'Guest password (8 characters minimum)',
        protected: 'Protected by password',
        public: 'Public',
        retention: 'Retention in days',
        retentionHint: 'Leave blank for unlimited gallery retention.',
        retentionUnlimited: 'Keep this gallery indefinitely',
        unlimited: 'Unlimited',
        save: 'Save settings',
        settings: 'Settings',
        settingsTitle: 'Settings — {{title}}',
        title: 'Event title',
        updateError: 'The settings could not be saved. Review the fields and try again.',
        updated: 'Settings saved.',
        view: 'View gallery',
        visibility: {
          draft: 'Draft',
          offline: 'Offline',
          published: 'Published',
          unlisted: 'Unlisted',
        },
      },
      language: 'Français',
      login: {
        body: 'Sign in with the private owner credential configured for this deployment.',
        configuration: 'Administration is locked because authentication is not configured. Add the required Worker secrets, then redeploy.',
        error: 'We could not sign you in. Check your password and try again.',
        eyebrow: 'Owner access',
        demoLink: 'Curious? Open the read-only demo',
        password: 'Password',
        submit: 'Sign in',
        title: 'Photographer sign in',
        turnstileUnavailable: 'The security check is not ready. Please refresh and try again.',
      },
      logout: 'Sign out',
      navigation: {
        dashboard: 'Dashboard',
        settings: 'Site settings',
      },
      settings: {
        description: 'Choose the default language and colour experience visitors receive across the public website and galleries.',
        eyebrow: 'Public website',
        error: 'The site settings could not be loaded or saved. Please try again.',
        loading: 'Loading site settings…',
        language: 'Default visitor language',
        languageEn: 'English',
        languageFr: 'French',
        languageHint: 'Used for new visitors. A visitor can still change language from the public website.',
        readOnly: 'The demo shows the real owner control. Saving is intentionally blocked by the Worker.',
        save: 'Save public settings',
        saved: 'Public settings saved.',
        themeBoth: 'Let visitors choose light or dark',
        themeDark: 'Always use dark theme',
        themeHint: 'Visitor choice shows a Light / Dark switch in the public header. Fixed modes remove it; System follows each visitor’s device.',
        themeLight: 'Always use light theme',
        themeMode: 'Visitor colour theme',
        themeSystem: 'Follow each visitor’s system setting',
        title: 'Site settings',
      },
      signedInAs: 'Signed in as {{subject}}',
      skipToContent: 'Skip to content',
      theme: 'Use dark theme',
      themeLight: 'Use light theme',
    },
  },
  fr: {
    admin: {
      dashboard: {
        description: 'Votre espace événement est prêt pour les prochaines étapes.',
        events: 'Gestion des événements',
        eventsDescription: 'Créez, publiez et importez les galeries depuis cet espace.',
        title: 'Tableau de bord',
      },
      demo: {
        dashboardBody: "Parcourez la même structure d'événements qu'un photographe. La création, la modification, les imports, les téléversements, la publication, l'indexation faciale et la suppression sont bloqués par le serveur pour cette session.",
        dashboardTitle: 'Explorez le parcours en toute sécurité.',
        eyebrow: 'Démonstration produit en direct',
        importBody: "Les outils d'import et de publication sont réservés au compte propriétaire. Cette identité de démo ne peut ni téléverser de fichiers ni modifier les données Cloudflare.",
        importTitle: 'Imports désactivés en lecture seule',
        inspect: 'Voir les réglages de la galerie',
        capabilitiesTitle: 'Actions du propriétaire',
        capabilitiesBody: "Voici les mêmes prochaines étapes que pour un propriétaire. Elles restent visibles afin de présenter le parcours, mais le Worker bloque chaque action dans cette démo.",
        formPlayground: 'Essayez librement chaque option. Seule l’action finale d’enregistrement est désactivée, et le Worker reste la frontière de sécurité.',
        createGallery: 'Créer une galerie',
        importPhotos: 'Importer des photos',
        publishGallery: 'Publier la galerie',
        loginBody: "Utilisez les identifiants publics ci-dessous. Ce compte peut parcourir le tableau de bord, mais ne peut rien créer, modifier, téléverser, publier ou supprimer.",
        loginTitle: "Explorez l'espace photographe.",
        ownerLink: 'Photographe? Utiliser la connexion propriétaire',
        readOnlyBanner: 'Mode démo — lecture seule. Toute requête qui modifierait des données est bloquée par le Worker.',
        readOnlyLabel: "Détails de l'événement en lecture seule",
        status: 'État',
        submit: 'Entrer dans la démo en lecture seule',
        username: "Nom d'utilisateur",
      },
      events: {
        access: 'Accès à la galerie',
        allowDownloads: 'Autoriser le téléchargement des photos',
        back: 'Retour aux événements',
        create: "Créer l'événement brouillon",
        createDescription: "Commencez avec un brouillon privé. Importez et révisez les photos avant de le publier.",
        createError: "Impossible de créer l'événement. Vérifiez les champs et réessayez.",
        createTitle: 'Nouvel événement',
        date: "Date et heure de l'événement",
        description: 'Description',
        empty: 'Aucun événement. Créez votre premier brouillon ci-dessus.',
        faceSearch: 'Activer la recherche faciale facultative',
        nearbySearch: 'Inclure les photos des moments rapprochés',
        nearbySearchHint: 'Disponible uniquement avec la recherche faciale. Ajoute les photos de la même galerie prises autour d’une correspondance possible.',
        showPhotoMetadata: 'Permettre aux visiteurs de voir les métadonnées des photos',
        import: 'Importer des photos',
        keepOriginals: 'Conserver les fichiers originaux',
        listError: 'Impossible de charger les événements.',
        listTitle: 'Vos événements',
        loading: 'Chargement des événements…',
        newPassword: "Nouveau mot de passe invité (laissez vide pour conserver l'actuel)",
        notFound: "Cet événement est introuvable.",
        options: 'Options de la galerie',
        password: 'Mot de passe invité (8 caractères minimum)',
        protected: 'Protégée par mot de passe',
        public: 'Publique',
        retention: 'Conservation en jours',
        retentionHint: 'Laissez vide pour une conservation illimitée de la galerie.',
        retentionUnlimited: 'Conserver cette galerie sans limite de durée',
        unlimited: 'Illimitée',
        save: 'Enregistrer les réglages',
        settings: 'Réglages',
        settingsTitle: 'Réglages — {{title}}',
        title: "Titre de l'événement",
        updateError: "Impossible d'enregistrer les réglages. Vérifiez les champs et réessayez.",
        updated: 'Réglages enregistrés.',
        view: 'Voir la galerie',
        visibility: {
          draft: 'Brouillon',
          offline: 'Hors ligne',
          published: 'Publiée',
          unlisted: 'Non répertoriée',
        },
      },
      language: 'English',
      login: {
        body: 'Connectez-vous avec le secret privé du propriétaire configuré pour ce déploiement.',
        configuration: "L'administration est verrouillée parce que l'authentification n'est pas configurée. Ajoutez les secrets Worker requis, puis redéployez.",
        error: 'La connexion a échoué. Vérifiez votre mot de passe et réessayez.',
        eyebrow: 'Accès propriétaire',
        demoLink: 'Curieux? Ouvrir la démo en lecture seule',
        password: 'Mot de passe',
        submit: 'Se connecter',
        title: 'Connexion photographe',
        turnstileUnavailable: 'La vérification de sécurité est indisponible. Actualisez puis réessayez.',
      },
      logout: 'Se déconnecter',
      navigation: {
        dashboard: 'Tableau de bord',
        settings: 'Réglages du site',
      },
      settings: {
        description: 'Choisissez la langue par défaut et l’expérience de couleur offertes aux visiteurs du site public et des galeries.',
        eyebrow: 'Site public',
        error: "Impossible de charger ou d’enregistrer les réglages du site. Réessayez.",
        loading: 'Chargement des réglages du site…',
        language: 'Langue visiteur par défaut',
        languageEn: 'Anglais',
        languageFr: 'Français',
        languageHint: 'Utilisée pour les nouveaux visiteurs. Un visiteur peut toujours changer de langue depuis le site public.',
        readOnly: 'La démo affiche le vrai contrôle propriétaire. L’enregistrement est intentionnellement bloqué par le Worker.',
        save: 'Enregistrer les réglages publics',
        saved: 'Réglages publics enregistrés.',
        themeBoth: 'Laisser les visiteurs choisir clair ou sombre',
        themeDark: 'Toujours utiliser le thème sombre',
        themeHint: 'Le choix visiteur affiche un interrupteur Clair / Sombre dans l’en-tête public. Les modes fixes le retirent ; Système suit l’appareil de chaque visiteur.',
        themeLight: 'Toujours utiliser le thème clair',
        themeMode: 'Thème de couleur visiteur',
        themeSystem: 'Suivre les réglages système de chaque visiteur',
        title: 'Réglages du site',
      },
      signedInAs: 'Connecté en tant que {{subject}}',
      skipToContent: 'Aller au contenu',
      theme: 'Utiliser le thème sombre',
      themeLight: 'Utiliser le thème clair',
    },
  },
} as const;
