/**
 * PA-owned resource fragment. The integration owner merges each language into
 * the existing `translation` resource before mounting AdminRoutes.
 */
export const adminResourceFragment = {
  en: {
    admin: {
      dashboard: {
        description: 'Create a gallery, add photos, then choose when to share it.',
        events: 'Gallery management',
        eventsDescription: 'Open a gallery to add photos, change its settings, or share it with visitors.',
        title: 'Dashboard',
      },
      demo: {
        dashboardBody: 'Open a gallery to explore its settings, or try the new-gallery options below. Nothing you change in this demo will be saved.',
        dashboardTitle: 'Explore the gallery workspace.',
        eyebrow: 'Live product demonstration',
        importBody: 'Photo uploads and publishing are unavailable in this demo. You can explore the options without changing anything.',
        importTitle: 'Imports are disabled in read-only mode',
        inspect: 'View gallery settings',
        capabilitiesTitle: 'Owner actions',
        capabilitiesBody: 'Explore the steps involved in preparing a gallery. This demo does not save changes.',
        formPlayground: 'Try any option. Saving is turned off in this demo.',
        createGallery: 'Create a gallery',
        importPhotos: 'Import photos',
        publishGallery: 'Publish gallery',
        loginBody: 'Use the sign-in details below to explore the gallery workspace. This demo cannot change galleries or photos.',
        loginTitle: 'Explore the gallery workspace.',
        ownerLink: 'Manage this site? Use the owner sign-in',
        readOnlyBanner: 'Demo mode — explore freely. Changes cannot be saved.',
        readOnlyLabel: 'Read-only gallery details',
        status: 'Status',
        submit: 'Enter the read-only demo',
        username: 'Username',
      },
      events: {
        access: 'Gallery access',
        allowDownloads: 'Allow photo downloads',
        back: 'Back to galleries',
        create: 'Create draft gallery',
        createDescription: 'Give your gallery a name and date, choose who can see it, then add photos before publishing.',
        createError: 'The gallery could not be created. Review the fields and try again.',
        createTitle: 'New gallery',
        date: 'Gallery date',
        dangerEyebrow: 'Danger zone',
        delete: 'Delete gallery',
        deleteTitle: 'Permanently delete this gallery',
        deleteCancel: 'Keep gallery',
        deleteConfirm: 'Permanently delete gallery',
        deleteConfirmationLabel: 'Type the gallery title to confirm',
        deleteDescription: 'Visitors lose access right away. The gallery, its photos, and face-search data are then permanently removed; cleanup may take some time.',
        deleteDialogBody: 'This cannot be undone. To confirm, type the gallery title exactly as shown below.',
        deleteDialogTitle: 'Permanently delete this gallery?',
        deleteError: 'We could not start deleting this gallery. Check the title and try again.',
        deleting: 'Starting deletion…',
        deletionPending: 'Deletion in progress',
        description: 'Description',
        empty: 'No galleries yet. Create your first draft below.',
        faceSearch: 'Enable optional face search',
        nearbySearch: 'Include photos from nearby moments',
        nearbySearchHint: 'Available with face search. Visitors can also see photos taken just before or after a possible match in this gallery.',
        showPhotoMetadata: 'Show photo details to visitors (date, image size, file name)',
        showOnGalleryPage: 'Show in public gallery lists',
        showOnGalleryPageHint: 'Turn off to remove this gallery from the Galleries page and the home page. Its direct link still works once published.',
        import: 'Import photos',
        keepOriginals: 'Offer original files',
        keepOriginalsHint: 'New imports keep the original for download. Otherwise visitors receive the best prepared copy.',
        originalsWarningTitle: 'Original files are still stored',
        originalsImportTitle: 'An original-file import is unfinished',
        originalsWarningBody: '{{count}} original files ({{amount}} {{unit}}) remain in this gallery, although visitors now receive prepared copies or cannot download photos.',
        originalsCleanupPending: 'Removing original files in the background. This notice will disappear when cleanup finishes.',
        originalsImportsPending: 'An original-file import is unfinished. Finish it or cancel it before removing stored originals.',
        originalsAbandonImports: 'Cancel unfinished imports',
        originalsAbandonTitle: 'Cancel unfinished imports?',
        originalsAbandonBody: 'This stops unfinished original-file imports for this gallery. Photos already completed remain. You can then remove stored originals.',
        originalsAbandonConfirm: 'Cancel imports',
        originalsCleanupFailed: 'Cleanup could not finish. Try again.',
        originalsDelete: 'Delete stored originals',
        originalsCancel: 'Keep originals',
        originalsDeleteConfirm: 'Delete originals',
        originalsDialogTitle: 'Delete stored originals?',
        originalsDialogBody: 'This permanently removes original files from this gallery. Prepared gallery photos and their downloads remain available. You cannot undo this or recreate the originals without importing them again.',
        originalsCleanupError: 'Cleanup could not be started. Try again.',
        originalsStatusError: 'Could not check whether this gallery still stores original files. Refresh to try again.',
        coverTitle: 'Gallery cover',
        coverDescription: 'Choose a photo for this gallery’s card. Only ready photos appear here.',
        coverCurrent: 'Current cover',
        coverLoading: 'Loading photos…',
        coverError: 'The photos could not be loaded.',
        coverEmpty: 'Import photos to choose a cover.',
        coverChoose: 'Use {{filename}} as the gallery cover',
        coverMore: 'Show more photos',
        coverClear: 'Remove cover',
        coverSaveError: 'The cover could not be saved. Try again.',
        listError: 'Galleries could not be loaded.',
        listTitle: 'Your galleries',
        loading: 'Loading galleries…',
        newPassword: 'New guest password (leave empty to keep the current password)',
        notFound: 'This gallery could not be found.',
        options: 'Gallery options',
        password: 'Guest password (8 characters minimum)',
        protected: 'Protected by password',
        protectedListingHint: 'When listed publicly, the title, date and description are visible. The password protects the photos.',
        public: 'Public',
        retention: 'Retention in days',
        retentionHint: 'Leave blank if you do not want this gallery to expire automatically.',
        retentionUnlimited: 'No automatic expiry',
        unlimited: 'No automatic expiry',
        save: 'Save settings',
        settings: 'Settings',
        settingsSectionTitle: 'Gallery details and options',
        settingsTitle: 'Settings — {{title}}',
        title: 'Gallery title',
        updateError: 'The settings could not be saved. Review the fields and try again.',
        updated: 'Settings saved.',
        view: 'View gallery',
        visibility: {
          draft: 'Draft',
          offline: 'Offline',
          published: 'Published',
          unlisted: 'Unlisted',
        },
      },
      favorites: {
        back: 'Back to gallery settings',
        eyebrow: 'Client selections',
        title: 'Client photo choices — {{title}}',
        description: 'Photos marked for retouching by guests appear here. Download them, edit them as usual, then replace them here. Their links and favorites stay in place.',
        viewLabel: 'Photo lists',
        retouchView: 'To retouch',
        favoritesView: 'Favorites',
        favoriteCount_one: '{{count}} favorite photo',
        favoriteCount_other: '{{count}} favorite photos',
        favoriteEmpty: 'No favorites yet. Guests can use the heart in the private gallery.',
        listLabel: 'Selected photos',
        count_one: '{{count}} selected photo',
        count_other: '{{count}} selected photos',
        empty: 'No photos have been selected for retouching yet. Guests can use the check mark in the private gallery.',
        loading: 'Loading selected photos…',
        error: 'Selected photos could not be loaded. Refresh and try again.',
        open: 'Client photo choices',
        sectionTitle: 'Client selections',
        sectionDescription: 'See the photos guests marked for retouching, download them, and replace them after editing. Favorites remain separate.',
        download: 'Download',
        replace: 'Replace photo',
        sampleNotReplaceable: 'This showcase photo is refreshed with the demo. Import your own private gallery to try replacing an edited photo.',
        updated: 'Edited version in gallery',
        finishReplacement: 'Finish replacement',
        replaceError: 'The replacement could not be finished. Try again.',
        more: 'Show more selected photos',
        saveShown: 'Save {{count}} shown photos',
        saveZip: 'Prepare ZIP of photos {{first}}–{{last}}',
        downloadZip: 'Download prepared ZIP',
        progress: '{{count}} photos prepared',
        cancel: 'Cancel',
        downloadError: 'The download could not finish. Try again or download photos one at a time.',
      },
      language: 'Français',
      login: {
        body: 'Enter your password to manage your galleries and website.',
        configuration: 'Sign-in is not ready yet. Check the setup guide or ask the person who installed this site.',
        error: 'We could not sign you in. Check your password and try again.',
        eyebrow: 'Owner access',
        demoLink: 'Curious? Open the read-only demo',
        password: 'Password',
        submit: 'Sign in',
        title: 'Photographer sign in',
        turnstileUnavailable: 'The security check is not ready. Please refresh and try again.',
      },
      logout: 'Sign out',
      navigation: {
        dashboard: 'Dashboard',
        settings: 'Site settings',
      },
      settings: {
        websiteSection: 'Website',
        sectionsLabel: 'Site setting sections',
        servicesSection: 'Services',
        contactSection: 'Contact',
        siteName: 'Studio or website name',
        servicesHint: 'Choose the services shown on the home and Services pages. Keep at least one enabled.',
        service: { wedding: 'Weddings & events', family: 'Portraits & families', brand: 'Photos for your brand', corporate: 'Workplace photography', children: 'Children’s portraits' },
        contactHint: 'These details appear on your Contact page. Leave a field blank to hide it. Saved changes appear on the website shortly afterward.',
        contactEmail: 'Email address',
        contactPhone: 'Phone number',
        contactAddress: 'Studio location',
        serviceArea: 'Where you travel',
        serviceAreaHint: 'A short description for visitors. This is different from your studio address; for example, “Montréal and the South Shore”.',
        serviceAreaPlaceholder: 'Montréal and the South Shore',
        mapTitle: 'Service-area map',
        mapHint: 'Search for the city at the centre of your service area, then enter how far you travel. You can also enter coordinates yourself. Leave all three map fields blank to hide the map.',
        mapCity: 'Find a city',
        mapCityPlaceholder: 'Start typing a city name',
        mapCityHint: 'Choose a suggestion to fill in the map coordinates. This optional search contacts a map provider.',
        mapCityLoading: 'Looking for cities…',
        mapCityEmpty: 'No city found. Try a fuller name or enter coordinates below.',
        mapCityError: 'City suggestions are unavailable. You can enter coordinates below.',
        mapLatitude: 'Centre latitude',
        mapLongitude: 'Centre longitude',
        mapRadius: 'Travel distance (km)',
        formError: 'Choose at least one service and complete all three map fields, or clear all three.',
        analyticsMeasurementId: 'Google Analytics ID',
        analyticsHint: 'Optional. Paste your Google Analytics ID (for example, G-XXXXXXXXXX), or leave this blank to turn it off. Visits are counted only when a visitor agrees.',
        description: 'Choose what visitors see on your website. Save your changes to update your contact details, services, languages, and appearance.',
        eyebrow: 'Public website',
        error: 'The site settings could not be loaded or saved. Please try again.',
        loading: 'Loading site settings…',
        language: 'Default visitor language',
        languageEn: 'English',
        languageFr: 'French',
        languageHint: 'Used for new visitors. If you offer more than one language, they can switch on the public website.',
        languages: 'Available visitor languages',
        languagesHint: 'Choose one or more. With one language, the public language control is hidden.',
        countUsageValue: '{{used}} of {{limit}}',
        faceLimit: 'Maximum faces saved for photo search',
        faceLimitHint: 'Choose a limit of up to {{maximum}} faces across this site’s galleries.',
        faceUsage: 'Faces saved for photo search',
        galleryLimit: 'Maximum separate galleries',
        galleryLimitHint: 'This counts galleries, not photos. Each gallery can hold up to 2,000 photos. You can set a limit of up to {{maximum}} galleries.',
        galleryUsage: 'Galleries',
        quotasDescription: 'Set limits for this site. Lowering a limit does not delete anything already saved, but you cannot add more until you are under it.',
        quotasScope: 'These limits help you manage galleries, photos, and face search. They do not guarantee that your whole Cloudflare account will stay free; check your account usage there.',
        quotasTitle: 'Your site limits',
        quotasSection: 'Usage & limits',
        readOnly: 'You can explore these settings, but changes cannot be saved in this demo.',
        save: 'Save public settings',
        saved: 'Public settings saved.',
        themeBoth: 'Let visitors choose light or dark',
        themeDark: 'Always use dark theme',
        themeHint: 'Visitor choice shows a Light / Dark switch in the public header. Fixed modes remove it; System follows each visitor’s device.',
        themeLight: 'Always use light theme',
        themeMode: 'Visitor colour theme',
        themeSystem: 'Follow each visitor’s system setting',
        title: 'Site settings',
        storageLimit: 'Maximum space for photos (GB)',
        storageLimitHint: 'Choose a limit of up to {{maximum}} GB for this site’s photos.',
        storageUsage: 'Photo storage',
        storageUsageValue: '{{used}} {{unit}} of {{limit}} GB',
        storageUnits: { bytes: 'B', kilobytes: 'kB', megabytes: 'MB', gigabytes: 'GB' },
      },
      signedInAs: 'Signed in as {{subject}}',
      skipToContent: 'Skip to content',
      theme: 'Use dark theme',
      themeLight: 'Use light theme',
    },
  },
  fr: {
    admin: {
      dashboard: {
        description: 'Créez une galerie, ajoutez des photos, puis choisissez quand la partager.',
        events: 'Gestion des galeries',
        eventsDescription: 'Ouvrez une galerie pour ajouter des photos, modifier ses réglages ou la partager.',
        title: 'Tableau de bord',
      },
      demo: {
        dashboardBody: 'Ouvrez une galerie pour explorer ses réglages ou essayez les options de création ci-dessous. Rien de ce que vous modifiez dans cette démo ne sera enregistré.',
        dashboardTitle: 'Explorez la gestion des galeries.',
        eyebrow: 'Démonstration produit en direct',
        importBody: 'L’ajout de photos et la publication sont indisponibles dans cette démo. Vous pouvez explorer les options sans rien modifier.',
        importTitle: 'Imports désactivés en lecture seule',
        inspect: 'Voir les réglages de la galerie',
        capabilitiesTitle: 'Actions du propriétaire',
        capabilitiesBody: 'Explorez les étapes de préparation d’une galerie. Cette démo n’enregistre aucun changement.',
        formPlayground: 'Essayez les options qui vous intéressent. L’enregistrement est désactivé dans cette démo.',
        createGallery: 'Créer une galerie',
        importPhotos: 'Importer des photos',
        publishGallery: 'Publier la galerie',
        loginBody: 'Utilisez les informations de connexion ci-dessous pour explorer la gestion des galeries. Cette démo ne peut pas modifier les galeries ou les photos.',
        loginTitle: 'Explorez la gestion des galeries.',
        ownerLink: 'Vous gérez ce site ? Utilisez la connexion propriétaire',
        readOnlyBanner: 'Mode démo — explorez librement. Les changements ne peuvent pas être enregistrés.',
        readOnlyLabel: 'Détails de la galerie en lecture seule',
        status: 'État',
        submit: 'Entrer dans la démo en lecture seule',
        username: "Nom d'utilisateur",
      },
      events: {
        access: 'Accès à la galerie',
        allowDownloads: 'Autoriser le téléchargement des photos',
        back: 'Retour aux galeries',
        create: 'Créer la galerie brouillon',
        createDescription: 'Nommez la galerie, choisissez sa date et son accès, puis ajoutez des photos avant de la publier.',
        createError: 'Impossible de créer la galerie. Vérifiez les champs et réessayez.',
        createTitle: 'Nouvelle galerie',
        date: 'Date de la galerie',
        dangerEyebrow: 'Zone dangereuse',
        delete: 'Supprimer la galerie',
        deleteTitle: 'Supprimer définitivement cette galerie',
        deleteCancel: 'Conserver la galerie',
        deleteConfirm: 'Supprimer définitivement la galerie',
        deleteConfirmationLabel: 'Saisissez le titre de la galerie pour confirmer',
        deleteDescription: 'Les visiteurs perdent aussitôt l’accès. La galerie, ses photos et les données de recherche faciale sont ensuite supprimées définitivement; cette opération peut prendre du temps.',
        deleteDialogBody: 'Cette action est irréversible. Pour confirmer, saisissez exactement le titre affiché ci-dessous.',
        deleteDialogTitle: 'Supprimer définitivement cette galerie?',
        deleteError: 'Nous n’avons pas pu commencer la suppression. Vérifiez le titre et réessayez.',
        deleting: 'Début de la suppression…',
        deletionPending: 'Suppression en cours',
        description: 'Description',
        empty: 'Aucune galerie. Créez votre premier brouillon ci-dessous.',
        faceSearch: 'Activer la recherche faciale facultative',
        nearbySearch: 'Inclure les photos des moments rapprochés',
        nearbySearchHint: 'Disponible avec la recherche faciale. Les visiteurs peuvent aussi voir les photos prises juste avant ou après une ressemblance possible dans cette galerie.',
        showPhotoMetadata: 'Afficher les détails des photos aux visiteurs (date, dimensions, nom du fichier)',
        showOnGalleryPage: 'Afficher dans les listes publiques de galeries',
        showOnGalleryPageHint: 'Décochez pour retirer la galerie de la page Galeries et de l’accueil. Son lien direct reste accessible une fois publiée.',
        import: 'Importer des photos',
        keepOriginals: 'Proposer les fichiers originaux',
        keepOriginalsHint: 'Les prochains imports conserveront l’original à télécharger. Sinon, les visiteurs recevront la meilleure copie préparée.',
        originalsWarningTitle: 'Des fichiers originaux sont encore stockés',
        originalsImportTitle: 'Un import de fichiers originaux est inachevé',
        originalsWarningBody: '{{count}} originaux ({{amount}} {{unit}}) restent dans cette galerie, même si les visiteurs reçoivent maintenant des copies préparées ou ne peuvent plus télécharger.',
        originalsCleanupPending: 'Suppression des originaux en arrière-plan. Cet avis disparaîtra à la fin du nettoyage.',
        originalsImportsPending: 'Un import d’originaux n’est pas terminé. Terminez-le ou annulez-le avant de supprimer les fichiers stockés.',
        originalsAbandonImports: 'Annuler les imports inachevés',
        originalsAbandonTitle: 'Annuler les imports inachevés ?',
        originalsAbandonBody: 'Cette action arrête les imports d’originaux inachevés de cette galerie. Les photos déjà terminées restent disponibles. Vous pourrez ensuite supprimer les originaux stockés.',
        originalsAbandonConfirm: 'Annuler les imports',
        originalsCleanupFailed: 'Le nettoyage n’a pas abouti. Réessayez.',
        originalsDelete: 'Supprimer les originaux stockés',
        originalsCancel: 'Conserver les originaux',
        originalsDeleteConfirm: 'Supprimer les originaux',
        originalsDialogTitle: 'Supprimer les originaux stockés ?',
        originalsDialogBody: 'Cette action supprime définitivement les originaux de cette galerie. Les photos préparées et leurs téléchargements restent disponibles. Pour retrouver les originaux, il faudra les importer de nouveau.',
        originalsCleanupError: 'Impossible de lancer le nettoyage. Réessayez.',
        originalsStatusError: 'Impossible de vérifier les fichiers originaux encore stockés. Actualisez la page pour réessayer.',
        coverTitle: 'Couverture de la galerie',
        coverDescription: 'Choisissez la photo affichée sur la carte de cette galerie. Seules les photos prêtes sont proposées.',
        coverCurrent: 'Couverture actuelle',
        coverLoading: 'Chargement des photos…',
        coverError: 'Impossible de charger les photos.',
        coverEmpty: 'Importez des photos pour choisir une couverture.',
        coverChoose: 'Utiliser {{filename}} comme couverture de la galerie',
        coverMore: 'Voir plus de photos',
        coverClear: 'Retirer la couverture',
        coverSaveError: 'Impossible d’enregistrer la couverture. Réessayez.',
        listError: 'Impossible de charger les galeries.',
        listTitle: 'Vos galeries',
        loading: 'Chargement des galeries…',
        newPassword: "Nouveau mot de passe invité (laissez vide pour conserver l'actuel)",
        notFound: 'Cette galerie est introuvable.',
        options: 'Options de la galerie',
        password: 'Mot de passe invité (8 caractères minimum)',
        protected: 'Protégée par mot de passe',
        protectedListingHint: 'Si la galerie figure dans les listes publiques, son titre, sa date et sa description sont visibles. Le mot de passe protège les photos.',
        public: 'Publique',
        retention: 'Conservation en jours',
        retentionHint: 'Laissez vide si vous ne voulez pas que cette galerie expire automatiquement.',
        retentionUnlimited: 'Aucune expiration automatique',
        unlimited: 'Aucune expiration automatique',
        save: 'Enregistrer les réglages',
        settings: 'Réglages',
        settingsSectionTitle: 'Détails et options de la galerie',
        settingsTitle: 'Réglages — {{title}}',
        title: 'Titre de la galerie',
        updateError: "Impossible d'enregistrer les réglages. Vérifiez les champs et réessayez.",
        updated: 'Réglages enregistrés.',
        view: 'Voir la galerie',
        visibility: {
          draft: 'Brouillon',
          offline: 'Hors ligne',
          published: 'Publiée',
          unlisted: 'Non répertoriée',
        },
      },
      favorites: {
        back: 'Retour aux réglages de la galerie',
        eyebrow: 'Sélection des clients',
        title: 'Choix des clients — {{title}}',
        description: 'Les photos sélectionnées pour retouche par les invités apparaissent ici. Téléchargez-les, retouchez-les, puis remplacez-les. Leurs liens et coups de cœur restent en place.',
        viewLabel: 'Listes de photos',
        retouchView: 'À retoucher',
        favoritesView: 'Coups de cœur',
        favoriteCount_one: '{{count}} coup de cœur',
        favoriteCount_other: '{{count}} coups de cœur',
        favoriteEmpty: 'Aucun coup de cœur pour le moment. Les invités peuvent utiliser le cœur dans la galerie privée.',
        listLabel: 'Photos sélectionnées',
        count_one: '{{count}} photo sélectionnée',
        count_other: '{{count}} photos sélectionnées',
        empty: 'Aucune photo n’a encore été sélectionnée pour retouche. Les invités peuvent utiliser la coche dans la galerie privée.',
        loading: 'Chargement des photos sélectionnées…',
        error: 'Impossible de charger les photos sélectionnées. Actualisez la page et réessayez.',
        open: 'Choix des clients',
        sectionTitle: 'Sélection des clients',
        sectionDescription: 'Retrouvez les photos sélectionnées pour retouche, téléchargez-les et remplacez-les ensuite. Les coups de cœur restent distincts.',
        download: 'Télécharger',
        replace: 'Remplacer la photo',
        sampleNotReplaceable: 'Cette photo de démonstration est remise à jour avec la démo. Importez votre propre galerie privée pour essayer le remplacement après retouche.',
        updated: 'Version retouchée dans la galerie',
        finishReplacement: 'Terminer le remplacement',
        replaceError: 'Impossible de terminer le remplacement. Réessayez.',
        more: 'Voir plus de photos sélectionnées',
        saveShown: 'Enregistrer les {{count}} photos affichées',
        saveZip: 'Préparer un ZIP des photos {{first}} à {{last}}',
        downloadZip: 'Télécharger le ZIP préparé',
        progress: '{{count}} photos préparées',
        cancel: 'Annuler',
        downloadError: 'Le téléchargement n’a pas abouti. Réessayez ou téléchargez les photos une par une.',
      },
      language: 'English',
      login: {
        body: 'Entrez votre mot de passe pour gérer vos galeries et votre site.',
        configuration: 'La connexion n’est pas encore prête. Consultez le guide d’installation ou demandez à la personne qui a installé ce site.',
        error: 'La connexion a échoué. Vérifiez votre mot de passe et réessayez.',
        eyebrow: 'Accès propriétaire',
        demoLink: 'Curieux? Ouvrir la démo en lecture seule',
        password: 'Mot de passe',
        submit: 'Se connecter',
        title: 'Connexion photographe',
        turnstileUnavailable: 'La vérification de sécurité est indisponible. Actualisez puis réessayez.',
      },
      logout: 'Se déconnecter',
      navigation: {
        dashboard: 'Tableau de bord',
        settings: 'Réglages du site',
      },
      settings: {
        websiteSection: 'Site Web',
        sectionsLabel: 'Sections des réglages du site',
        servicesSection: 'Services',
        contactSection: 'Contact',
        siteName: 'Nom du studio ou du site',
        servicesHint: 'Choisissez les services affichés sur l’accueil et la page Services. Gardez-en au moins un.',
        service: { wedding: 'Mariages et événements', family: 'Portraits et familles', brand: 'Photos pour votre marque', corporate: 'Photos d’entreprise', children: 'Portraits d’enfants' },
        contactHint: 'Ces coordonnées apparaissent sur votre page Contact. Laissez un champ vide pour le masquer. Les changements enregistrés apparaîtront peu après sur le site.',
        contactEmail: 'Adresse courriel',
        contactPhone: 'Numéro de téléphone',
        contactAddress: 'Emplacement du studio',
        serviceArea: 'Où vous vous déplacez',
        serviceAreaHint: 'Une courte description pour vos visiteurs, différente de l’adresse du studio. Par exemple : « Montréal et la Rive-Sud ».',
        serviceAreaPlaceholder: 'Montréal et la Rive-Sud',
        mapTitle: 'Carte de la zone de service',
        mapHint: 'Cherchez la ville au centre de votre zone de service, puis indiquez jusqu’où vous vous déplacez. Vous pouvez aussi entrer les coordonnées vous-même. Laissez les trois champs de la carte vides pour la masquer.',
        mapCity: 'Rechercher une ville',
        mapCityPlaceholder: 'Commencez à écrire le nom d’une ville',
        mapCityHint: 'Choisissez une suggestion pour remplir les coordonnées de la carte. Cette recherche facultative contacte un fournisseur de cartes.',
        mapCityLoading: 'Recherche des villes…',
        mapCityEmpty: 'Aucune ville trouvée. Essayez un nom plus complet ou saisissez les coordonnées ci-dessous.',
        mapCityError: 'Les suggestions de villes sont indisponibles. Vous pouvez saisir les coordonnées ci-dessous.',
        mapLatitude: 'Latitude du centre',
        mapLongitude: 'Longitude du centre',
        mapRadius: 'Distance de déplacement (km)',
        formError: 'Choisissez au moins un service et remplissez les trois champs de la carte, ou videz-les tous.',
        analyticsMeasurementId: 'Identifiant Google Analytics',
        analyticsHint: 'Facultatif. Collez votre identifiant Google Analytics (par exemple G-XXXXXXXXXX), ou laissez ce champ vide pour désactiver le suivi. Les visites ne sont comptées qu’avec l’accord du visiteur.',
        description: 'Choisissez ce que les visiteurs voient sur votre site. Enregistrez pour mettre à jour vos coordonnées, services, langues et couleurs.',
        eyebrow: 'Site public',
        error: "Impossible de charger ou d’enregistrer les réglages du site. Réessayez.",
        loading: 'Chargement des réglages du site…',
        language: 'Langue visiteur par défaut',
        languageEn: 'Anglais',
        languageFr: 'Français',
        languageHint: 'Utilisée pour les nouveaux visiteurs. Si vous offrez plusieurs langues, ils peuvent en changer sur le site public.',
        languages: 'Langues offertes aux visiteurs',
        languagesHint: 'Choisissez une ou plusieurs langues. Avec une seule langue, le sélecteur public est masqué.',
        countUsageValue: '{{used}} sur {{limit}}',
        faceLimit: 'Nombre maximal de visages conservés pour la recherche',
        faceLimitHint: 'Choisissez une limite allant jusqu’à {{maximum}} visages pour toutes les galeries de ce site.',
        faceUsage: 'Visages conservés pour la recherche',
        galleryLimit: 'Nombre maximal de galeries distinctes',
        galleryLimitHint: 'Cette limite compte les galeries, pas les photos. Chaque galerie peut contenir jusqu’à 2 000 photos. Vous pouvez fixer une limite allant jusqu’à {{maximum}} galeries.',
        galleryUsage: 'Galeries',
        quotasDescription: 'Fixez des limites pour ce site. Les réduire ne supprime rien de ce qui est déjà enregistré, mais vous ne pourrez plus en ajouter avant de repasser sous la limite.',
        quotasScope: 'Ces limites vous aident à gérer les galeries, les photos et la recherche faciale. Elles ne garantissent pas que tout votre compte Cloudflare restera gratuit; vérifiez aussi votre utilisation là-bas.',
        quotasTitle: 'Limites de votre site',
        quotasSection: 'Usage et limites',
        readOnly: 'Vous pouvez explorer ces réglages, mais les changements ne peuvent pas être enregistrés dans cette démo.',
        save: 'Enregistrer les réglages publics',
        saved: 'Réglages publics enregistrés.',
        themeBoth: 'Laisser les visiteurs choisir clair ou sombre',
        themeDark: 'Toujours utiliser le thème sombre',
        themeHint: 'Le choix visiteur affiche un interrupteur Clair / Sombre dans l’en-tête public. Les modes fixes le retirent ; Système suit l’appareil de chaque visiteur.',
        themeLight: 'Toujours utiliser le thème clair',
        themeMode: 'Thème de couleur visiteur',
        themeSystem: 'Suivre les réglages système de chaque visiteur',
        title: 'Réglages du site',
        storageLimit: 'Espace maximal pour les photos (Go)',
        storageLimitHint: 'Choisissez une limite allant jusqu’à {{maximum}} Go pour les photos de ce site.',
        storageUsage: 'Espace occupé par les photos',
        storageUsageValue: '{{used}} {{unit}} sur {{limit}} Go',
        storageUnits: { bytes: 'o', kilobytes: 'ko', megabytes: 'Mo', gigabytes: 'Go' },
      },
      signedInAs: 'Connecté en tant que {{subject}}',
      skipToContent: 'Aller au contenu',
      theme: 'Utiliser le thème sombre',
      themeLight: 'Utiliser le thème clair',
    },
  },
} as const;
