export const serviceEditorResources = {
  en: { admin: { serviceEditor: {
    loading: 'Loading sessions…', error: 'The session could not be saved. Check the translations, photo, and connection, then try again.',
    saved: 'Session saved.', newService: 'New session', hidden: 'Hidden', enabled: 'Show on the Sessions page',
    showOnHome: 'Include on Home', photo: 'Session photo', photoRequired: 'Upload a photo before showing this new session.',
    framing: 'Photo framing', framingHint: 'Choose which side stays visible when the photo fills its frame. This keeps the full image. Save the session to apply your choice.',
    desktopAlignment: 'Default focal point', mobileAlignment: 'Phone focal point', sameAlignment: 'Use the default focal point',
    desktopPreview: 'Default crop preview', mobilePreview: 'Phone Home preview',
    alignment: { left: 'Left', center: 'Center', right: 'Right', top: 'Top', bottom: 'Bottom' },
    title: 'Title', shortDescription: 'Short Home description', description: 'Session description', point: 'Included detail {{number}}',
    duration: 'Session duration (optional)', priceRange: 'Price or price range (optional)', details: 'More information for the session dialog (optional)',
    save: 'Save session', create: 'Create session', add: 'Add a session',
    homeSummary: '{{count}} sessions selected for Home.',
    onHome: 'On Home', moveUp: 'Move {{name}} up', moveDown: 'Move {{name}} down',
  } } },
  fr: { admin: { serviceEditor: {
    loading: 'Chargement des séances…', error: 'La séance n’a pas pu être enregistrée. Vérifiez les traductions, la photo et la connexion, puis réessayez.',
    saved: 'Séance enregistrée.', newService: 'Nouvelle séance', hidden: 'Masqué', enabled: 'Afficher sur la page Séances',
    showOnHome: 'Inclure sur l’accueil', photo: 'Photo de la séance', photoRequired: 'Téléversez une photo avant d’afficher cette nouvelle séance.',
    framing: 'Cadrage de la photo', framingHint: 'Choisissez le côté à garder visible lorsque la photo remplit son cadre. L’image entière est conservée. Enregistrez la séance pour appliquer votre choix.',
    desktopAlignment: 'Point d’ancrage par défaut', mobileAlignment: 'Point d’ancrage sur téléphone', sameAlignment: 'Utiliser le point d’ancrage par défaut',
    desktopPreview: 'Aperçu du cadrage par défaut', mobilePreview: 'Aperçu de l’accueil sur téléphone',
    alignment: { left: 'Gauche', center: 'Centre', right: 'Droite', top: 'Haut', bottom: 'Bas' },
    title: 'Titre', shortDescription: 'Courte description pour l’accueil', description: 'Description de la séance', point: 'Élément inclus {{number}}',
    duration: 'Durée de la séance (facultatif)', priceRange: 'Prix ou fourchette tarifaire (facultatif)', details: 'Informations pour la fenêtre de la séance (facultatif)',
    save: 'Enregistrer la séance', create: 'Créer la séance', add: 'Ajouter une séance',
    homeSummary: '{{count}} séances sélectionnées pour l’accueil.',
    onHome: 'Sur l’accueil', moveUp: 'Monter {{name}}', moveDown: 'Descendre {{name}}',
  } } },
} as const;
